---
#https://github.com/ohmyzsh/ohmyzsh/wiki

- name: Set zsh as default shell for {{username}}
  ansible.builtin.user:
    name: "{{username}}"
    shell: /bin/zsh

- name: Check if .oh-my-zsh exists  
  become: false
  stat:
    path: "/home/{{username}}/.oh-my-zsh"
  register: oh_my_zsh_dir

- name: Install oh-my-zsh
  when: not oh_my_zsh_dir.stat.exists
  become: false
  block:
    - name: Download oh-my-zsh installer
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "/home/{{username}}/install_omz.sh"
        mode: '755'

    - name: Run oh-my-zsh installer
      ansible.builtin.shell: "sh /home/{{username}}/install_omz.sh --unattended"

- name: Remove oh-my-zsh installer
  become: false
  ansible.builtin.file:
    path: "/home/{{username}}/install_omz.sh"
    state: absent

# https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest:  "/home/{{username}}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

# https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest:  "/home/{{username}}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

# https://github.com/supercrabtree/k

- name: Install k
  ansible.builtin.git:
    repo: 'https://github.com/supercrabtree/k'
    dest:  "/home/{{username}}/.oh-my-zsh/custom/plugins/k"

- name: Write .aliases
  copy:
    src: "templates/.aliases"
    dest: "/home/{{username}}/.aliases"     