---
- name: Get current user
  ansible.builtin.set_fact:
    setup_fedora_username: "{{ lookup('env', 'USER') }}"

- name: Enable passwordless sudo for {{ setup_fedora_username }}
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ setup_fedora_username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
