---
# https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions

- name: Get current user
  ansible.builtin.set_fact:
    setup_fedora_username: "{{ lookup('env', 'USER') }}"

- name: Add docker repository
  become: true
  ansible.builtin.yum_repository:
    name: docker
    description: Docker CE Stable
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/fedora/gpg

- name: Install docker engine
  become: true
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Docker group for {{ setup_fedora_username }}
  become: true
  ansible.builtin.user:
    name: "{{ setup_fedora_username }}"
    groups: docker
    append: true

- name: Start docker daemon
  become: true
  ansible.builtin.service:
    name: "docker"
    enabled: true
    state: started
