---
# https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions

- name: Add VS Code repository
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install VS Code
  ansible.builtin.dnf:
    name: code