---
#https://mullvad.net/en/download/vpn/linux

- name: Add Mullvad repository
  yum_repository:
    name: mullvad
    description: Mullvad VPN
    baseurl: https://repository.mullvad.net/rpm/stable/$basearch
    gpgcheck: yes
    gpgkey: https://repository.mullvad.net/rpm/mullvad-keyring.asc

- name: Install Mullvad
  ansible.builtin.dnf:
    name: mullvad-vpn